modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="crafterscobblemonnpc"
version="${file.jarVersion}"
displayName="Crafters Cobblemon NPC"
authors="Crafters CR"
logoFile="crafterscobblemonnpc_icon.png"
description='''
Permite crear Pokémon decorativos utilizando directamente
los modelos, animaciones y sonidos de Cobblemon.
'''

[[dependencies.crafterscobblemonnpc]]
modId="neoforge"
type="required"
versionRange="[21.1,22)"
ordering="NONE"
side="BOTH"

[[dependencies.crafterscobblemonnpc]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.crafterscobblemonnpc]]
modId="cobblemon"
type="required"
versionRange="[1.7.3,1.8.0)"
ordering="AFTER"
side="BOTH"